#!/bin/bash
set -euo pipefail


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE ${SWITCHBOARD_DB_READONLY_USER} WITH LOGIN PASSWORD '${SWITCHBOARD_DB_READONLY_PASSWORD}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${SWITCHBOARD_DB_READONLY_USER};
    GRANT USAGE ON SCHEMA public TO ${SWITCHBOARD_DB_READONLY_USER};
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${SWITCHBOARD_DB_READONLY_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${SWITCHBOARD_DB_READONLY_USER};

    CREATE ROLE ${SWITCHBOARD_DB_WRITE_USER} WITH LOGIN PASSWORD '${SWITCHBOARD_DB_WRITE_PASSWORD}';
    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${SWITCHBOARD_DB_WRITE_USER};
    GRANT USAGE ON SCHEMA public TO ${SWITCHBOARD_DB_WRITE_USER};
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${SWITCHBOARD_DB_WRITE_USER};
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${SWITCHBOARD_DB_WRITE_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${SWITCHBOARD_DB_WRITE_USER};
EOSQL
